/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prog2.ha1;

public class App {
    public String getGreeting() {
        return "Testausgabe"  ;  // return null;   return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
